- name: inetRouter
  hosts: inetRouter
  become: true
  tasks:
    
  - name: install epel-release
    yum:
      name: epel-release
      state: present

  - name: install knock-server
    yum:
      name: knock-server
      state: present

  - name: Copy knockd config
    template:
      src: templates/knockd.conf
      dest: /etc/knockd.conf

  - name: start knockd service
    service:
      name: knockd
      state: started
  
  - name : Add iptables rules
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 2222:4444
      jump: ACCEPT

  - name : sshd_config
    template:
      src: templates/sshd_config
      dest: /etc/ssh/sshd_config 
  
  - name: sshd restart
    service:
      name: sshd 
      state: restarted
  
- name: centralRouter
  hosts: centralRouter
  become: true
  tasks:

     - name: install epel-release centralRouter
       yum:
        name: epel-release
        state: present

     - name: install nmap and nginx
       yum:
        name: 
         - nmap
         - nginx
        state: present
    
     - name: start nginx
       service: 
          name: nginx
          state: started

     - name: copy knock script
       template:
          src: templates/knock.sh
          dest: /home/vagrant/knock.sh
          owner: vagrant
          group: vagrant
          mode: '0744'

     - name: route to host  
       become_user: root
       shell: ip route add 192.168.56.0/24 via 192.168.254.2 
       ignore_errors: true

- name: inetRouter2
  hosts: inetRouter2
  become: true
  tasks:
      - name: Forward port 8080 to 80
        iptables:
          table: nat
          chain: PREROUTING
          in_interface: eth2
          protocol: tcp
          match: tcp
          destination_port: "8080"
          jump: DNAT
          to_destination: "192.168.254.1:80"

          comment: Redirect web traffic to centralRouter
        become: yes
      
      # iptables -t nat -A PREROUTING -i eth2 -p tcp --dport 8080 -j DNAT --to-destination 192.168.254.1:80
    

