
---
- name: centralRouter
  hosts: centralRouter
  become: true
  tasks:
  - name: ADD route to office1 
    become_user: root
    shell: echo '192.168.1.0/24 via 192.168.255.6 dev eth5' > /etc/sysconfig/network-scripts/route-eth5
    ignore_errors: true

  - name: ADD route to office2
    become_user: root
    shell: echo '192.168.2.0/24 via 192.168.255.10 dev eth6' > /etc/sysconfig/network-scripts/route-eth6
    ignore_errors: true
  
  - name: ADD route to inet
    become_user: root
    shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 && echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    ignore_errors: true

- name: inetRouter
  hosts: inetRouter
  become: true
  tasks:
  - name: ADD route to inet
    become_user: root
    shell: echo '192.168.0.0/16 via 192.168.255.2 dev eth1' > /etc/sysconfig/network-scripts/route-eth1
    ignore_errors: true
    
- name: office1router
  hosts: office1router
  become: true
  tasks:
  - name: ADD default route
    become_user: root
    shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 && echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth5

- name: office2router
  hosts: office2router
  become: true
  tasks:
  - name: ADD default route
    become_user: root
    shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 

  - name: ADD default route eth4
    become_user: root
    shell: echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth4
  
- name: Network restart routers
  hosts: Routers
  become: true
  tasks:
     - name: Ensure network  is in a running state
       service:
          name: network 
          state: started
       register: networkDetails
       until: networkDetails.status.ActiveState == "active"
       retries: 5
       delay: 10
  
     - name: Network restart
       systemd:
          state: restarted
          name: network

     - name: forwarding enable 
       become_user: root
       shell: sysctl -w net.ipv4.conf.all.forwarding=1

 